# Generated by Django 2.2 on 2020-09-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customercart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercart',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customercartitem',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
